name: Simple python application

on:
  push:
    branches: [ main ]

jobs:

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

        # - name: Lint with flake8
        #   working-directory: ./src
        #   run: |
        #     flake8 .
      - name: Run unit test
        working-directory: ./src
        run: |
          python test.py
      - name: Zip installation
        run: |
          apt install zip -y
      - name: Zip lambda artifact
        working-directory: ./src
        run: |
          zip app.zip app.py
      - uses: actions/upload-artifact@master
        working-directory: ./src
        with:
          name: archive
          path: ./app.zip